module.exports = [
  'al', 'dz', 'ao', 'ai', 'ag', 'ar',
  'am', 'au', 'at', 'az', 'bs', 'bh',
  'bb', 'by', 'be', 'bz', 'bj', 'bm',
  'bt', 'bo', 'bw', 'br', 'vg', 'bn',
  'bg', 'bf', 'kh', 'ca', 'cv', 'ky',
  'td', 'cl', 'cn', 'co', 'cg', 'cr',
  'hr', 'cy', 'cz', 'dk', 'dm', 'do',
  'ec', 'eg', 'sv', 'ee', 'fj', 'fi',
  'fr', 'gm', 'de', 'gh', 'gr', 'gd',
  'gt', 'gw', 'gy', 'hn', 'hk', 'hu',
  'is', 'in', 'id', 'ie', 'il', 'it',
  'jm', 'jp', 'jo', 'kz', 'ke', 'kr',
  'kw', 'kg', 'la', 'lv', 'lb', 'lr',
  'lt', 'lu', 'mo', 'mk', 'mg', 'mw',
  'my', 'ml', 'mt', 'mr', 'mu', 'mx',
  'fm', 'md', 'mn', 'ms', 'mz', 'na',
  'np', 'nl', 'nz', 'ni', 'ne', 'ng',
  'no', 'om', 'pk', 'pw', 'pa', 'pg',
  'py', 'pe', 'ph', 'pl', 'pt', 'qa',
  'ro', 'ru', 'sa', 'sn', 'sc', 'sl',
  'sg', 'sk', 'si', 'sb', 'za', 'es',
  'lk', 'kn', 'lc', 'vc', 'sr', 'sz',
  'se', 'ch', 'st', 'tw', 'tj',
  'th', 'tt', 'tn', 'tr', 'tm', 'tc',
  'ug', 'ua', 'ae', 'gb', 'us', 'uy',
  'uz', 've', 'vn', 'ye', 'zw',
];
